apiVersion: apps/v1
kind: Deployment
metadata:
 name: configurationservicedeployment
spec:
 replicas: 1
 selector:
  matchLabels:
   appName: configurationservice
 template:
  metadata:
   labels:
    appName: configurationservice
  spec:
   containers:
    - name: configurationservicepods
      image: gryffindor937/configurationservicedeployment:1.0
      imagePullPolicy: Always
      env:
       - name: eureka_client_service-url_defaultZone
         valueFrom: 
          configMapKeyRef: 
           name: globalconfigmap
           key: eureka_client_service-url_defaultZone
      ports:
       - containerPort: 8762
---

apiVersion: v1
kind: Service
metadata:
 name: configurationservicelb
spec:
 selector:
  appName: configurationservice
 ports:
  - port: 8762
    targetPort: 8762
 type: LoadBalancer

---

apiVersion: v1
kind: ConfigMap
metadata:
 name: globalconfigmap
data:
 eureka_client_service-url_defaultZone: http://discoveryservicelb.default.svc.cluster.local:8761/eureka