apiVersion: apps/v1
kind: Deployment
metadata:
 name: notificationservicedeployment
spec:
 replicas: 1
 selector:
  matchLabels:
   appName: notificationservice
 template:
  metadata:
   labels:
    appName: notificationservice
  spec:
   containers:
    - name: discoveryservicepods
      image: gryffindor937/notificationservicedeployment:1.0
      imagePullPolicy: Always