apiVersion: apps/v1
kind: Deployment
metadata:
 name: orderservicedeployment
spec:
 replicas: 1
 selector:
  matchLabels:
   appName: orderservice
 template:
  metadata:
   labels:
    appName: orderservice
  spec:
   containers:
    - name: orderservicepods
      image: gryffindor937/orderservicedeployment:1.0
      imagePullPolicy: Always
      ports:
       - containerPort: 8087
---

apiVersion: v1
kind: Service
metadata:
 name: orderservicelb
spec:
 selector:
  appName: orderservice
 ports:
  - port: 8087
    targetPort: 8087
 type: LoadBalancer
 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orderingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /order
        pathType: Prefix
        backend:
          service:
            name: orderservicelb
            port:
              number: 8087