apiVersion: apps/v1
kind: Deployment
metadata:
 name: gatewayservicedeployment
spec:
 replicas: 1
 selector:
  matchLabels:
   appName: gatewayservice
 template:
  metadata:
   labels:
    appName: gatewayservice
  spec:
   containers:
    - name: gatewayservicepods
      image: gryffindor937/gatewayservicedeployment:1.0
      imagePullPolicy: Always
      ports:
       - containerPort: 8084
---

apiVersion: v1
kind: Service
metadata:
 name: gatewayservicelb
spec:
 selector:
  appName: gatewayservice
 ports:
  - port: 8084
    targetPort: 8084
 type: LoadBalancer