apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: kafkadeployment
spec:
 replicas: 1
 selector:
  matchLabels:
   appName: kafka
 template:
  metadata:
   labels:
    appName: kafka
  spec:
   hostname: kafakbroker01
   containers:
    - name: kafkapods
      image: bitnami/kafka:latest
      imagePullPolicy: Always
      ports:
       - containerPort: 9092
      volumeMounts:
      - name: kafkastorage
        mountPath: /bitnami/kafka
      env:
      - name: KAFKA_CFG_NODE_ID
        value: "0"
      - name: KAFKA_CFG_PROCESS_ROLES
        value: controller,broker
      - name: KAFKA_CFG_LISTENERS
        value: PLAINTEXT://:9092,CONTROLLER://:9093
      - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
        value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
        value: 0@localhost:9093
      - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
        value: CONTROLLER
      - name: KAFKA_ADVERTISED_HOST_NAME
        valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
   volumes:
   - name: kafkastorage
     persistentVolumeClaim:
      claimName: kafka-pvc
---

apiVersion: v1
kind: Service
metadata:
 name: kafkalb
spec:
 selector:
  appName: kafka
 ports:
  - port: 9092
    targetPort: 9092
 type: LoadBalancer