apiVersion: apps/v1
kind: Deployment
metadata:
 name: catalogservicedeployment
spec:
 replicas: 1
 selector:
  matchLabels:
   appName: catalogservice
 template:
  metadata:
   labels:
    appName: catalogservice
  spec:
   containers:
    - name: configurationservicepods
      image: gryffindor937/catalogservicedeployment:1.0
      imagePullPolicy: Always
      env:
       - name: eureka_client_service-url_defaultZone
         valueFrom: 
          configMapKeyRef: 
           name: globalconfigmap
           key: eureka_client_service-url_defaultZone
      ports:
       - containerPort: 8763
---

apiVersion: v1
kind: Service
metadata:
 name: catalogservicelb
spec:
 selector:
  appName: catalogservice
 ports:
  - port: 8763
    targetPort: 8763
 type: LoadBalancer

---

apiVersion: v1
kind: ConfigMap
metadata:
 name: globalconfigmap
data:
 eureka_client_service-url_defaultZone: http://discoveryservicelb.default.svc.cluster.local:8761/eureka