---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: elasticsearchdeployment
spec:
 replicas: 1
 selector:
  matchLabels:
   appName: elasticsearch
 template:
  metadata:
   labels:
    appName: elasticsearch
  spec:
   containers:
    - name: elasticsearchpods
      image: elasticsearch:8.13.3
      imagePullPolicy: Always
      env:
       - name: discovery.type
         value: single-node
       - name: xpack.security.enabled
         value: "false"
      ports:
       - containerPort: 9200
---

apiVersion: v1
kind: Service
metadata:
 name: elasticsearchlb
spec:
 selector:
  appName: elasticsearch
 ports:
  - port: 9200
    targetPort: 9200
 type: LoadBalancer